---
- name: Install Supervisord
  apt: name={{ item }} state=present
       update_cache=true cache_valid_time=7200
  with_items: 
    - supervisor

- name: Copy supervisord config file
  template:
    src: templates/supervisord.conf.j2
    dest: "{{ SUPERVISORD_CONF_FILE }}"

- name: Copy supervisord init script
  template:
    src: templates/supervisord.init.j2
    dest: /etc/init.d/supervisor
    mode: u+x,g+x

- name: Kill supervisord process if it is running
  command: pkill -f supervisord
  ignore_errors: true

- name: Ensure supervisord is running
  service:
    name: supervisor
    state: started
    enabled: yes