---
- name: Copy carbon repo
  git: clone=yes
       repo={{ item.repo }}
       dest={{ item.dir }}
       version={{ GRAPHITE_VERSON }}
  with_items:
    - { repo: "{{ CARBON_REPO }}", dir: "{{ GRAPHITE_DIR }}/carbon" }

- name: Install carbon dependencies
  pip: requirements={{ GRAPHITE_DIR }}/carbon/requirements.txt
       virtualenv={{ GRAPHITE_DIR }}  
