---
- name: Install carbon package
  pip: name=carbon
       virtualenv={{ GRAPHITE_DIR }}  

- name: Copy config file
  template: src=templates/carbon.conf.j2
            dest={{ GRAPHITE_DIR }}/conf/carbon.conf
  tags:
    - settings