---
- name: Install graphite web package
  pip: name=graphite-web
       virtualenv={{ GRAPHITE_DIR }}  

- name: Configure webapp
  template: src=templates/local_settings.py.j2
            dest={{ GRAPHITE_DIR }}/webapp/graphite/local_settings.py
            mode=0644
  tags:
    - settings

- name: Run syncdb
  command: "{{ GRAPHITE_DIR }}/bin/python python manage.py syncdb"
  args:
    chdir: "{{ GRAPHITE_DIR }}/webapp/graphite"

- name: Copy supervisor config
  template: src=templates/graphite-supervisord.conf.j2
            dest={{ SUPERVISORD_CONF_DIR }}/conf.d/graphite.conf
  tags:
    - settings

- name: Start graphite app
  supervisorctl: name={{ GRAPHITE_APP_NAME }}
                 state=started
                 config={{ SUPERVISORD_CONF_DIR }}/supervisord.conf
  tags:
    - activation