---
- name: Copy graphite-web repo
  git: clone=yes
       repo={{ item.repo }}
       dest={{ item.dir }}
       version={{ GRAPHITE_VERSON }}
  with_items:
    - { repo: "{{ GRAPHITE_WEB_REPO }}", dir: "{{ GRAPHITE_DIR }}/graphite-web" }

- name: Install graphite web dependencies
  pip: requirements={{ GRAPHITE_DIR }}/graphite-web/requirements.txt
     virtualenv={{ GRAPHITE_DIR }}  
