---

- name: Configure webapp
  template: src=templates/local_settings.py.j2
            dest={{ GRAPHITE_DIR }}/webapp/graphite/local_settings.py
            mode=0644
  tags:
    - settings

- name: Install dependencies
  pip: name={{ item }} state=present virtualenv={{ GRAPHITE_DIR }}
  with_items:
    - "django==1.8"

- name: Run syncdb
  command: bash -c "{{ GRAPHITE_DIR }}/bin/python manage.py migrate; {{ GRAPHITE_DIR }}/bin/python manage.py syncdb"
  args:
    chdir: "{{ GRAPHITE_DIR }}/webapp/graphite"
  ignore_errors: yes

- name: Copy WSGI config
  template: src=graphite.wsgi.j2
            dest={{ GRAPHITE_DIR }}/webapp/graphite/graphite_wsgi.py

- name: Copy supervisor config
  template: src=templates/graphite-supervisord.conf.j2
            dest={{ SUPERVISORD_CONF_DIR }}/conf.d/graphite.conf
  tags:
    - settings

- name: Start graphite app
  supervisorctl: name={{ GRAPHITE_APP_NAME }}
                 state=restarted
                 config={{ SUPERVISORD_CONF_DIR }}/supervisord.conf
  tags:
    - activation
