---
- name: Install whisper package
  pip: name=whisper
       virtualenv={{ GRAPHITE_DIR }}  

- name: Copy schema config file
  template: src=templates/storage-schemas.conf.j2
            dest={{ GRAPHITE_DIR }}/conf/storage-schemas.conf
  tags:
    - settings

- name: Copy aggregation config file
  template: src=templates/storage-aggregation.conf.j2
            dest={{ GRAPHITE_DIR }}/conf/storage-aggregation.conf
  tags:
    - settings
  notify:
    - restart supervisord