---
- name: Install whisper package
  pip: name=whisper
       virtualenv={{ GRAPHITE_DIR }}  

- name: Copy config file
  template: src=templates/storage-schemas.conf.j2
            dest={{ GRAPHITE_DIR }}/conf/storage-schemas.conf
  tags:
    - settings